blueprint:
  name: Notification on Scene Activated
  description: Send a Notification to people when a Scene is activated.
  domain: automation
  input:
    scene:
      name: 'Scene'
      description: 'The scene to send a notification about when activated.'
      selector:
        entity:
          domain: scene
    title:
      name: 'Title'
      description: 'The title of the notifcation.'
    message:
      name: 'Message'
      description: 'The message of the notifcation.'

trigger:
  platform: event
  event_type: call_service
  event_data: 
    domain: scene
    service: turn_on
    service_data:
      entity_id: !input scene

action:
  - service: notify.notify
    data:
      title: !input title
      message: !input message