blueprint:
  name: Notification on Scene Activated
  description: Send a Notification to people when a Scene is activated.
  domain: automation
  input:
    scene:

trigger:
  platform: event
  event_type: call_seervice
  event_data: 
    domain: scene
    service: turn_on
    service_data:
      entity_id: !input scene

action:
  service: notify.notify
    data:
      title: 'Title'
      message: 'Message'