blueprint:
  name: Notification on Scene Activated
  description: Send a Notification to people when a Scene is activated.
  domain: automation
  input:
    scene:
      name: 'Scene'
      description: 'The scene to send a notification about.'
      selector:
        entity:
          domain: scene
    test:
      name: 'Test'

trigger:
  platform: event
  event_type: call_seervice
  event_data: 
    domain: scene
    service: turn_on
    service_data:
      entity_id: !input scene

action:
  - service: notify.notify
    data:
      title: 'Title'
      message: 'Message'